name: logistics-terminal-simulator
static_sites:
  - name: website
    github:
      repo: AnurakChan/logistics
      branch: main
      deploy_on_push: true
    environment_slug: html
    build_command: npm run build
    output_dir: dist
    index_document: index.html
    catchall_document: index.html